# Generated by Django 4.2.14 on 2024-07-12 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='quetion',
            new_name='question',
        ),
    ]
